### ISSUE TITLE
LightsOn and XPerience

### ISSUE THREAD

**Issue by SShadow1974** [Carbon-Modding/Carbon.Core#53]
Having issues with LightsOn (https://umod.org/plugins/lights-on) and XPerience (https://umod.org/plugins/xperience):
Failed compiling 'C:\Rust Server Tool\carbon\plugins\XPerience.cs':
  1. Argument 3: cannot convert from 'Oxide.Core.Plugins.Plugin' to 'Oxide.Plugins.RustPlugin'
     (XPerience 88 line 9618)
[LightsOn] Timer 60s has failed: (Index was outside the bounds of the array.)
  at Oxide.Plugins.LightsOn.VehicleLiftChangePower () [0x00032] in <1713b71cc0034ce5b509c58cda7cc973>:0
  at Oxide.Plugins.LightsOn.<OnServerInitialized>b__65_18 () [0x00000] in <1713b71cc0034ce5b509c58cda7cc973>:0
  at Oxide.Plugins.Timers+<>c__DisplayClass13_0.<In>b__0 () [0x0000c] in <b4e67505d2444abb952cb6020f8025ce>:0

**Comment by SShadow1974** [comment]
Actually, a lot of RED text in my server console... Much more that scrolled by and I can't capture...

```
Failed to call hook 'OnServerInitialized' on plugin 'QualityCrafting v2.1.1' (Object reference not set to an instance of an object)
  at Carbon.HookCaller.CallHook[T] (Carbon.Base.BaseHookable plugin, System.String hookName, System.Object arg1, System.Object arg2, System.Object arg3) [0x0003b] in <b4e67505d2444abb952cb6020f8025ce>:0
  at Oxide.Core.Plugins.Plugin.Call[T] (System.String hook, System.Object arg1, System.Object arg2, System.Object arg3) [0x00001] in <b4e67505d2444abb952cb6020f8025ce>:0
  at Oxide.Plugins.QualityCrafting.LoadImages () [0x00020] in <bbe209fb79fe4edd97d827b33976968d>:0
  at Oxide.Plugins.QualityCrafting.OnServerInitialized (System.Boolean initial) [0x00037] in <bbe209fb79fe4edd97d827b33976968d>:0
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <fb001e01371b4adca20013e0ac763896>:0
Failed to call hook 'OnServerInitialized' on plugin 'RemoverTool v4.3.36' (Object reference not set to an instance of an object)
  at Oxide.Plugins.RemoverTool.AddImageToLibrary (System.String url, System.String shortname, System.UInt64 skin) [0x00021] in <23746acd6b8c4655880b2ad41e236e68>:0
  at Oxide.Plugins.RemoverTool.OnServerInitialized () [0x00286] in <23746acd6b8c4655880b2ad41e236e68>:0
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <fb001e01371b4adca20013e0ac763896>:0
```

**Comment by SShadow1974** [comment]
Carbon v0.2023.2108.1512

**Comment by raulssorban** [comment]
I fixed the first issue, please check out the latest Edge build. Testing now the other QualityCrafting issue. The RemoverTool plugin seems to not have access to ImageLibrary.

**Comment by SShadow1974** [comment]
Carbon v0.2023.2108.2025
It's working, still getting some red text in the console. No idea what any of this means, but maybe it does to you.
And Lights On is working.
```
at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <fb001e01371b4adca20013e0ac763896>:0
Failed to call hook 'OnCollectiblePickup' on plugin 'XPerience v1.7.3' (Object reference not set to an instance of an object)
  at Oxide.Plugins.XPerience.OnCollectiblePickup (CollectibleEntity collectible, BasePlayer player) [0x005c8] in <5514a261c9c742898cdaf4b8f980d0d4>:0
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <fb001e01371b4adca20013e0ac763896>:0
```
